<html>

<body>
    <h2>
        Do login
    </h2>

    <!-- <h2>Sign up using this form</h2> -->

    <?php echo $this->tag->form("login/loginuser"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("login"); ?>
    </p>

    </form>
</body>

</html>

<?php
