<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>



<?php

// print_r($users);

// echo $users[0]->user_id;
// echo $users->name;
// echo $users->email;

foreach ($users as $user)
    echo $user->name;
    
echo $user->email;
?>